# Generated by Django 3.0.5 on 2020-04-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200410_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/default.jpg', upload_to='profile_pics'),
        ),
    ]
